services:

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: piar_backend
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - SECRET_KEY=${SECRET_KEY}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - GOOGLE_REDIRECT_URI=${GOOGLE_REDIRECT_URI}
      - SMTP_SERVER=${SMTP_SERVER}
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_USER=${SMTP_USER}
      - SMTP_PASSWORD=${SMTP_PASSWORD}
      - SMTP_SENDER=${SMTP_SENDER}
      - SMTP_SENDER_NAME=${SMTP_SENDER_NAME}
      - SMTP_USE_TLS=${SMTP_USE_TLS}
      - FRONTEND_URL=${FRONTEND_URL}
      - CORS_ORIGINS=${CORS_ORIGINS}
      - OPENCLAW_API_KEY=${OPENCLAW_API_KEY}
      - OPENCLAW_API_URL=http://openclaw-gateway-piara:18789/v1/chat
      - OPENCLAW_AUTH_MODE=${OPENCLAW_AUTH_MODE}
      - OPENCLAW_PASSWORD=${OPENCLAW_GATEWAY_PASSWORD}
      - OPENCLAW_LOGIN_URL=http://openclaw-gateway-piara:18789/v1/login
      - OPENCLAW_BOTUSER_ID=${OPENCLAW_BOTUSER_ID}
      - OPENCLAW_BOTUSER_PASSWORD=${OPENCLAW_BOTUSER_PASSWORD}
    volumes:
      - piar_data:/app/data
    ports:
      - "8000:8000"
    networks:
      - piar-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        VITE_API_URL: /api
        VITE_APP_NAME: PiarAPP
        VITE_APP_VERSION: 0.1.0
        VITE_GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
        VITE_GOOGLE_REDIRECT_URI: ${GOOGLE_REDIRECT_URI}
    container_name: piar_frontend
    ports:
      - "8587:80"
    depends_on:
      - backend
    networks:
      - piar-network

  

  openclaw-gateway-piara:
    build:
      context: ./openclaw
    container_name: openclawPiara
    image: openclaw:latest
    environment:
      HOME: /data
      TZ: Europe/Madrid
      OPENCLAW_DOCTOR: "0"
      OPENCLAW_CONFIGURE: "0"
      GATEWAY_MODE: local
      OPENAI_API_KEY: "${OPENAI_API_KEY}"
      BRAVE_API_KEY: "${BRAVE_API_KEY}"
      OPENCLAW_GATEWAY_PASSWORD: "${OPENCLAW_GATEWAY_PASSWORD}"
      OPENCLAW_DEVICEID: "${OPENCLAW_DEVICEID}"
      OPENCLAW_DEVICEID_TOKEN: "${OPENCLAW_DEVICEID_TOKEN}"
      OPENCLAW_AUTH_TYPE: "${OPENCLAW_AUTH_TYPE}"
      OPENCLAW_PROVIDER: "${OPENCLAW_PROVIDER}"
      OPENCLAW_ACCESS_KEY: "${OPENCLAW_ACCESS_KEY}"
      OPENCLAW_REFRESH_KEY: "${OPENCLAW_REFRESH_KEY}"
      OPENCLAW_EXPIRES: "${OPENCLAW_EXPIRES}"
      OPENCLAW_ACCOUNTID: "${OPENCLAW_ACCOUNTID}"
      OPENCLAW_BOTUSER_ID: "${OPENCLAW_BOTUSER_ID}"
      OPENCLAW_BOTUSER_PASSWORD: "${OPENCLAW_BOTUSER_PASSWORD}"
    expose:
      - "18789"
    restart: unless-stopped
    stdin_open: True
    tty: True
    volumes:
      - piara_openclaw:/data
      - ./openclaw/data/.config:/data/.config
      - ./openclaw/data/.openclaw:/data/.openclaw
    networks:
      - piar-network

networks:
  piar-network:
    driver: bridge

volumes:
  piar_data:
  piara_openclaw:
